"""Add roles and user relations

Revision ID: 16c2384d450f
Revises: afd5c93a1408
Create Date: 2026-03-20 14:28:23.798174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c2384d450f'
down_revision: Union[str, None] = 'afd5c93a1408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.add_column('tenants', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['user_id'])
    op.create_foreign_key(None, 'tenants', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'user_id')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'owner_id')
    # ### end Alembic commands ###
