"""add_user_profile_contract_passport_fields

Revision ID: 32aed9e4a786
Revises: a3b0021f8e53
Create Date: 2026-05-06 10:18:39.180834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32aed9e4a786'
down_revision: Union[str, None] = 'a3b0021f8e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lease_contracts', sa.Column('signing_city', sa.String(), nullable=True))
    op.add_column('lease_contracts', sa.Column('signing_date', sa.Date(), nullable=True))
    op.add_column('lease_contracts', sa.Column('landlord_passport', sa.String(), nullable=True))
    op.add_column('lease_contracts', sa.Column('landlord_address', sa.String(), nullable=True))
    op.add_column('lease_contracts', sa.Column('tenant_passport', sa.String(), nullable=True))
    op.add_column('lease_contracts', sa.Column('tenant_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('patronymic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('lease_contracts', 'tenant_address')
    op.drop_column('lease_contracts', 'tenant_passport')
    op.drop_column('lease_contracts', 'landlord_address')
    op.drop_column('lease_contracts', 'landlord_passport')
    op.drop_column('lease_contracts', 'signing_date')
    op.drop_column('lease_contracts', 'signing_city')
    # ### end Alembic commands ###
