"""add_currency_support

Revision ID: 7b20d7e90bf0
Revises: a8322c6fc1ff
Create Date: 2026-05-06 16:21:50.974905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b20d7e90bf0'
down_revision: Union[str, None] = 'a8322c6fc1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, create the enum type
    currency_enum = sa.Enum('byn', 'eur', 'rub', 'usd', name='currency')
    currency_enum.create(op.get_bind(), checkfirst=True)
    
    # Then add columns with default values
    op.add_column('properties', sa.Column('currency', sa.Enum('byn', 'eur', 'rub', 'usd', name='currency'), nullable=False, server_default='byn'))
    op.add_column('lease_contracts', sa.Column('currency', sa.Enum('byn', 'eur', 'rub', 'usd', name='currency'), nullable=False, server_default='byn'))
    op.add_column('payments', sa.Column('currency', sa.Enum('byn', 'eur', 'rub', 'usd', name='currency'), nullable=False, server_default='byn'))
    
    # Remove server defaults after setting them
    op.alter_column('properties', 'currency', server_default=None)
    op.alter_column('lease_contracts', 'currency', server_default=None)
    op.alter_column('payments', 'currency', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lease_contracts', 'currency')
    op.drop_column('payments', 'currency')
    op.drop_column('properties', 'currency')
    # Drop the enum type
    sa.Enum('byn', 'eur', 'rub', 'usd', name='currency').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
