"""add_lat_lng_to_properties

Revision ID: a8322c6fc1ff
Revises: e9622943bd40
Create Date: 2026-05-06 11:48:47.334967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8322c6fc1ff'
down_revision: Union[str, None] = 'e9622943bd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    # ### end Alembic commands ###
