"""add_contract_type

Revision ID: eb09d5635c1f
Revises: fda3271a7f4d
Create Date: 2026-03-20 19:25:56.404740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb09d5635c1f'
down_revision: Union[str, None] = 'fda3271a7f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('standard', 'short_term', 'commercial', name='leasecontracttype').create(op.get_bind())
    op.add_column('lease_contracts', sa.Column('contract_type', sa.Enum('standard', 'short_term', 'commercial', name='leasecontracttype'), nullable=False, server_default='standard'))
    op.alter_column('properties', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('properties', 'amenities',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'amenities',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('properties', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_column('lease_contracts', 'contract_type')
    sa.Enum(name='leasecontracttype').drop(op.get_bind())
    # ### end Alembic commands ###
