"""Add marketplace fields to property and user

Revision ID: fda3271a7f4d
Revises: 16c2384d450f
Create Date: 2026-03-20 14:50:22.949066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fda3271a7f4d'
down_revision: Union[str, None] = '16c2384d450f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('rooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('total_floors', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_column('properties', 'amenities')
    op.drop_column('properties', 'images')
    op.drop_column('properties', 'total_floors')
    op.drop_column('properties', 'floor')
    op.drop_column('properties', 'rooms')
    # ### end Alembic commands ###
